services:
  app:
    build: .
    ports:
      - "4040:4040"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=passpass
      - DB_NAME=gamershub
    depends_on:
      - db

  db:
      image: postgres:16.9-alpine
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=passpass
        - POSTGRES_DB=gamershub
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      restart: unless-stopped

volumes:
  postgres_data: